SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';





-- tables gestion cache

CREATE  TABLE IF NOT EXISTS `elmt_has_cache` (
  `idelmt_has_cache` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `idelmt` BIGINT UNSIGNED NOT NULL ,
  `elmt` VARCHAR(127) NULL ,
  `typeelmt` VARCHAR(127) NULL ,
  `lang` VARCHAR(10) NULL DEFAULT 'fr_fr',
  `iduser` BIGINT UNSIGNED NOT NULL ,
  `cachedest` VARCHAR(255) NULL ,
  `date` DATETIME NULL ,
  PRIMARY KEY (`idelmt_has_cache`) )
ENGINE = MyISAM;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;