SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';






-- tables gestion token

CREATE  TABLE IF NOT EXISTS `token` (
  `idtoken` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `token` VARCHAR(255) NULL ,
  `typetoken` VARCHAR(25) NULL ,
  `iduser` BIGINT UNSIGNED NOT NULL ,
  PRIMARY KEY (`idtoken`) )
ENGINE = MyISAM;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;