SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';




CREATE  TABLE IF NOT EXISTS `menu` (
  `idmenu` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodemenu` VARCHAR(255) NULL ,
  `zone` VARCHAR(255) NULL ,
  `titre` VARCHAR(255) NULL ,
  `lien` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  `lang` VARCHAR(10) NULL DEFAULT 'fr_fr',
  `ordre` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`idmenu`,`nomcodemenu`) )
ENGINE = MyISAM;



CREATE  TABLE IF NOT EXISTS `menu_has_ssmenu` (
  `idmenu` BIGINT UNSIGNED NOT NULL ,
  `idssmenu` BIGINT UNSIGNED NOT NULL ,
  PRIMARY KEY (`idmenu`,`idssmenu`) )
ENGINE = MyISAM;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;